### ISSUE TITLE
Streamlit WebApp For The Beginner Python Projects Course

### ISSUE THREAD

**Issue by Outsiders17711** [kying18/beginner-projects#3]
[![Streamlit App](https://static.streamlit.io/badges/streamlit_badge_black_white.svg)](https://share.streamlit.io/outsiders17711/Beginner-Python-Projects-WebApp/main/beginnerPythonProjectsWebApp.py)

Hello Kylie,

I took your `12 Beginner Python Projects Course` on YouTube  and I really enjoyed it. So, I messed around a bit and created a Streamlit webapp for all the games in the course.  You can check it out **[here](https://share.streamlit.io/outsiders17711/Beginner-Python-Projects-WebApp/main/beginnerPythonProjectsWebApp.py)**. The source repository is **[here](https://github.com/Outsiders17711/Beginner-Python-Projects-WebApp)**. I hope it comes in handy.

Thanks for taking the time to create those videos. I learnt a lot from them.

Cheers.

![Short Demo](https://github.com/Outsiders17711/Beginner-Python-Projects-WebApp/blob/main/demo/beginnerPythonProjectsWebApp.gif?raw=true)

**Comment by kying18** [comment]
Hi Oluwaleke,

Not sure if you will receive this message, but this is AWESOME. Thank you for sharing. I will share this with the whole freeCodeCamp team :)

Let me know if I can tag you on instagram or twitter.

Best,

Kylie

**Comment by Outsiders17711** [comment]
Hey Kylie,

I got it. Thanks. But hey, it's all your code really. I just wrapped it up. 

I don't do social media but you can link the app or the repository so folks can find the source code.

Gracias.
